variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test
  - distribute

before_script:
  - earthly bootstrap

test_amd64:
  stage: test
  image: earthly/earthly:v0.6.30
  only:
    - main
    - merge_requests
  tags:
    - linux
    - amd64
  script:
    - earthly --ci +unit-tests-linux-amd64
  when: manual

distribute_amd64:
  stage: distribute
  needs:
    - job: test_amd64
  only:
    - stable
  tags:
    - linux
    - amd64
  script:
    - earthly +package-linux-amd64
    - /home/gitlab-runner/distribute-packages.sh
