variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test
  - package
  - distribute

before_script:
  - earthly bootstrap

build_amd64:
  stage: build
  only:
    - main
    - merge_requests
  image: earthly/earthly:v0.6.30
  tags:
    - linux
    - amd64
  script:
    - earthly +build-linux-amd64
  when: manual

test_amd64:
  stage: test
  needs:
    - job: build_amd64
  only:
    - TC/CICD-hacking
  tags:
    - main
    - amd64
  script:
    - earthly +unit-tests-linux-amd64

package_amd64:
  stage: package
  needs:
    - job: test_amd64
  only:
    - main
  tags:
    - linux
    - amd64
  script:
    - earthly +package-linux-amd64


distribute_amd64:
  stage: distribute
  needs:
    - job: package_amd64
  only:
    - main
  tags:
    - linux
    - amd64
  script:
    - /home/gitlab-runner/distribute-packages.sh


#earthly-arm64:
#  stage: linux-arm64
#  only:
#    - main
#    - merge_requests
#  image: earthly/earthly:v0.6.30
#  tags:
#    - linux
#    - amd64
#  script:
#    - earthly --ci -P +package-linux-arm64
