variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"


before_script:
  - earthly bootstrap

earthly:
  stage: build
  image: earthly/earthly:v0.6.30
  tags:
    - linux
    - amd64
  script:
    - earthly --ci -P +package-linux
