variables:
  NO_DOCKER: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - linux-amd64
  - linux-arm64

before_script:
  - earthly bootstrap

earthly-amd64:
  stage: linux-amd64
  only:
    - main
    - merge_requests
  image: earthly/earthly:v0.6.30
  tags:
    - linux
    - amd64
  script:
    - earthly --ci -P +package-linux-amd64

earthly-arm64:
  stage: linux-arm64
  only:
    - main
    - merge_requests
  image: earthly/earthly:v0.6.30
  tags:
    - linux
    - amd64
  script:
    - earthly --ci -P +package-linux-arm64
