name: Sync with GitLab

on:
  # schedule:
  #   - cron:  '0 * * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Add GitLab remote
      run: |
        git remote add gitlab https://gitlab.com/debanjanbasu/veilid.git

    - name: Fetch from GitLab
      run: |
        git fetch gitlab

    - name: Merge changes
      run: |
        git merge gitlab/main --allow-unrelated-histories -m "Sync with GitLab"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}